/**
 * @file main.c
 * @brief PMIC Clone Tool — main application entry point.
 *
 * STM32 HAL build: runs the CLI via UART interrupt-driven RX.
 * Host build:      runs an interactive terminal session for testing.
 */

#include "pmic_platform.h"
#include "pmic_i2c.h"
#include "pmic_regmap.h"
#include "pmic_clone.h"
#include "pmic_storage.h"
#include "pmic_cli.h"

/* ================================================================
 * Global instances
 * ================================================================ */

static pmic_i2c_t   g_i2c;
static clone_ctx_t   g_clone;
static cli_ctx_t     g_cli;

/* ================================================================
 * STM32 HAL entry point
 * ================================================================ */

#ifdef STM32_HAL

extern I2C_HandleTypeDef hi2c1;  /* From CubeMX-generated code */
extern UART_HandleTypeDef huart2;

static uint8_t rx_byte;

/**
 * @brief UART RX complete callback — feeds characters to the CLI.
 */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart == &huart2) {
        cli_process_char(&g_cli, (char)rx_byte);
        HAL_UART_Receive_IT(&huart2, &rx_byte, 1);
    }
}

int main(void)
{
    /* STM32 HAL init (generated by CubeMX) */
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();

    /* Initialize PMIC tool subsystems */
    pmic_i2c_init(&g_i2c, &hi2c1);
    storage_init();

    /* Default to first built-in profile */
    const pmic_profile_t *default_prof = pmic_profile_get(0);
    clone_init(&g_clone, &g_i2c, default_prof);

    /* Initialize CLI */
    cli_init(&g_cli, &g_clone, &g_i2c);
    cli_print_banner();
    cli_print_prompt(&g_cli);

    /* Start UART receive interrupt */
    HAL_UART_Receive_IT(&huart2, &rx_byte, 1);

    /* Main loop — nothing to do, everything is interrupt-driven */
    while (1) {
        HAL_Delay(100);
    }
}

#endif /* STM32_HAL */

/* ================================================================
 * Host build entry point (for PC testing)
 * ================================================================ */

#ifdef HOST_BUILD

#include <stdio.h>

/* Dummy I2C handle for host builds */
static int dummy_i2c_handle = 0;

int main(void)
{
    /* Initialize subsystems */
    pmic_i2c_init(&g_i2c, &dummy_i2c_handle);
    storage_init();

    /* Default to first built-in profile */
    const pmic_profile_t *default_prof = pmic_profile_get(0);
    clone_init(&g_clone, &g_i2c, default_prof);

    /* Initialize CLI */
    cli_init(&g_cli, &g_clone, &g_i2c);
    cli_print_banner();
    cli_print_prompt(&g_cli);

    /* Interactive loop: read characters from stdin */
    int c;
    while ((c = getchar()) != EOF) {
        cli_process_char(&g_cli, (char)c);
    }

    platform_printf("\r\nExiting.\r\n");
    return 0;
}

#endif /* HOST_BUILD */
